### PR TITLE
some minor fixes to the Dockerfile

### PR DESCRIPTION
**Pull request by sroegner**
- suppress apt-get readline warnings
- added --force-yes for extras installation to succeed

Nice project!

### CODE REVIEW

**Comment by nicolasff** [comment]
Merged, thanks @sroegner!

**Comment by nicolasff** [comment]
@sroegner `inetutils-ping` seems to fail on Ubuntu with docker, although I can verify that this package exists on my Ubuntu desktop. Do you know the source of this divergence?

**Comment by sroegner** [comment]
Which tag? Plain Ubuntu? I tried to reproduce on a number of different tag versions - none of which seemed to have ping but some come with iputils-ping pre-installed. Some of them suggested iputils-ping or inetutils-ping - I guess iputils-ping would be the safe choice? Can you try that?

**Comment by nicolasff** [comment]
Thanks, `iputils-ping` seems to work.

**Pull request merged**
